version: "3.3"
services:
  web:
    container_name: web
    build: ./Docker/web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Docker/logs/web:/var/log
    links:
      - redis
      - pgsql
  redis:
    container_name: redis
    image: redis
  pgsql:
    image: postgres:14.4
    container_name: pgsql
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=password1234